find_audience_segment:
  description: >
    Analyze the following targeting query: {query}.
    Use the audience segment data from the knowledge base to identify and rank the best matching segments.
  expected_output: |
    Return results in Markdown format with:
    - Segment name
    - Age group, income range, engagement recency
    - Reach and CPM
    - A short rationale for each
  agent: segment_agent

