select_segment_task:
  description: >
    Recommend the top audience segments that best match the campaign query: "{query}".
    Use only the indexed data from the segments.json file and never invent names or traits.

    Prioritize segments that match:
    1. Demographic fit (age, income, location)
    2. Recency of engagement
    3. Confidence and CPM

    Return each with:
    - Name
    - TaxonomyId
    - Age Range
    - Income Level
    - Location Type
    - Recency
    - CPM
    - Confidence
    - Estimated Reach
  expected_output: >
    A markdown formatted list of the top 3–5 recommended segments, including all specified fields.
  agent: segment_agent

validate_segment_task:
  description: >
    Validate whether the recommended segments truly align with the campaign query: "{query}".
    Cross-check all traits (taxonomyId, age range, income, recency, CPM) against the official segment data.

    If any segment does not match the query traits, clearly list the mismatches.
  expected_output: >
    A validation report in markdown format, confirming valid segments and listing any mismatches with reasons.
  agent: verifier_agent
  depends_on: [select_segment_task]
