select_segment_task:
  description: >
    Recommend the top audience segments that best match the campaign query: "{query}".
    Use only the indexed data from the segments.json file and never invent names or traits.

    Prioritize segments that match:
    1. Demographic fit (age, income, location)
    2. Recency of engagement
    3. Confidence and CPM

    Return each with:
    - Name
    - TaxonomyId
    - Age Range
    - Income Level
    - Location Type
    - Recency
    - CPM
    - Confidence
    - Estimated Reach
  expected_output: >
    A markdown formatted list of the top 3–5 recommended segments, including all specified fields.
  agent: segment_agent

validate_segment_task:
  description: >
    Validate whether the recommended segments truly align with the campaign query: "{query}".
    Cross-check all traits (taxonomyId, age range, income, recency, CPM) against the official segment data.

    For each segment, include:
    - Name
    - TaxonomyId
    - Age Range: Matches or Mismatch (with reasoning)
    - Income Level: Matches or Mismatch (with reasoning)
    - Location Type: Matches or Mismatch (with reasoning)
    - Recency: Matches or Mismatch (with reasoning)
    - CPM: Matches or Mismatch (with reasoning, if applicable)

  expected_output: >
    A markdown-formatted validation report for each segment, showing all fields above. If a segment has any mismatch, specify the reason. End the report with a summary listing which segments are fully valid.
  agent: verifier_agent
  depends_on: [select_segment_task]

